// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iocwcduckoasqchanfxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvY3djZHVja29hc3FjaGFuZnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODA0OTgsImV4cCI6MjA2NjY1NjQ5OH0.LSbKjGuoi6iU1VlRnOEBQA6eeFna-ttDrvPMIzFfiT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);